# Generated by Django 4.0.3 on 2023-03-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_accountvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
